export const games = [
    {
        id:1,
        img: new URL("../img/games/cyberpunk.jpg", import.meta.url).href,
        title: "Cyberpunk 2077",
        price: 2999,
        ratings: 4.6,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["action","fav"],
    },
    {
        id:2,
        img: new URL("../img/games/detroit.jpg", import.meta.url).href,
        title: "Detroit Became Human",
        price: 2499,
        ratings: 4.8,
        platform: ["PC","|","PS5"],
        iswishlist: false,
        type: ["story", "fav"],
    },
    {
        id:3,
        img: new URL("../img/games/gow-4.jpg", import.meta.url).href,
        title: "God Of War 2018",
        price: 2199,
        ratings: 4.7,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["story"],
    },
    {
        id:4,
        img: new URL("../img/games/gow-5.jpg", import.meta.url).href,
        title: "God Of War Ragnarok",
        price: 2999,
        ratings: 5,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["story","fav"],
    },
    {
        id:5,
        img: new URL("../img/games/gta5.jpg", import.meta.url).href,
        title: "Grand Theft Auto 5",
        price: 1599,
        ratings: 4.5,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["story","action"],
    },
    {
        id:6,
        img: new URL("../img/games/last-of-us-1.jpg", import.meta.url).href,
        title: "The Last Of Us Part 1",
        price: 2799,
        ratings: 4.8,
        platform: ["PC","|","PS5"],
        iswishlist: false,
        type: ["story"],
    },
    {
        id:7,
        img: new URL("../img/games/last-of-us-2.jpg", import.meta.url).href,
        title: "The Last Of Us Part 2",
        price: 2999,
        ratings: 5,
        platform: ["PC","|","PS5"],
        iswishlist: false,
        type: ["story","fav"],
    },
    {
        id:8,
        img: new URL("../img/games/little-nightmares-2.jpg", import.meta.url).href,
        title: "Little Nightmares 2",
        price: 1599,
        ratings: 4.5,
        platform: ["PC","|","PS5"],
        iswishlist: false,
        type: "horror",
    },
    {
        id:9,
        img: new URL("../img/games/rdr2.jpg", import.meta.url).href,
        title: "Red Dead Redemption 2",
        price: 2999,
        ratings: 4.8,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["story"],
    },
    {
        id:10,
        img: new URL("../img/games/spiderman-miles.jpg", import.meta.url).href,
        title: "Spider-Man Miles Morales",
        price: 2899,
        ratings: 4.7,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["action", "fav"],
    },
    {
        id:11,
        img: new URL("../img/games/stray.jpg", import.meta.url).href,
        title: "Stray",
        price: 1299,
        ratings: 4.5,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: "story",
    },
    {
        id:12,
        img: new URL("../img/games/tomb-raider.jpg", import.meta.url).href,
        title: "Rise Of The Tomb Raider",
        price: 2899,
        ratings: 4.7,
        platform: ["PC","|","PS5","|","XBOX"],
        iswishlist: false,
        type: ["action", "fav"],
    },
];